### ISSUE TITLE
Crash When Loaded With JEI

### ISSUE THREAD

**Issue by ghost** [SquidDev-CC/ccjam-2016#101]
I have Plethora 1.12.2-1.1.11 and JEI 1.12.2-4.8.5.159. Removing JEI allows the game to load, but I will need JEI in order to know how to craft modded items. Here is the stacktrace.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MixinLoaderForge (Valkyrien Warfare 0.9_pre_3 [HotFix].jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.8.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.7-core.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.174.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 4/16/18 8:48 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.ClassCastException: org.squiddev.plethora.gameplay.neural.NeuralItemHandler cannot be cast to net.minecraftforge.fluids.capability.IFluidHandler
	at mezz.jei.plugins.vanilla.ingredients.ItemStackListFactory$FluidSubtypeInterpreter.apply(ItemStackListFactory.java:147)
	at mezz.jei.api.ISubtypeRegistry$ISubtypeInterpreter.getSubtypeInfo(ISubtypeRegistry.java:87)
	at mezz.jei.runtime.SubtypeRegistry.getSubtypeInfo(SubtypeRegistry.java:50)
	at mezz.jei.startup.StackHelper.getUniqueIdentifierForStack(StackHelper.java:383)
	at mezz.jei.startup.StackHelper.getUniqueIdentifierForStack(StackHelper.java:360)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackHelper.getUniqueId(ItemStackHelper.java:42)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackHelper.getUniqueId(ItemStackHelper.java:16)
	at mezz.jei.recipes.RecipeMap.addRecipeCategory(RecipeMap.java:48)
	at mezz.jei.recipes.RecipeRegistry.<init>(RecipeRegistry.java:106)
	at mezz.jei.startup.ModRegistry.createRecipeRegistry(ModRegistry.java:302)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:64)
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:118)
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:759)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.3
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1715498344 bytes (1636 MB) / 3943170048 bytes (3760 MB) up to 5818023936 bytes (5548 MB)
	JVM Flags: 3 total; -Xmx6241m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2657 95 mods loaded, 95 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                          | Version                  | Source                                           | Signature                                |
	|:------ |:--------------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| UCHIJA | minecraft                   | 1.12.2                   | minecraft.jar                                    | None                                     |
	| UCHIJA | mcp                         | 9.42                     | minecraft.jar                                    | None                                     |
	| UCHIJA | FML                         | 8.0.99.99                | forge-1.12.2-14.23.3.2657.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                       | 14.23.3.2657             | forge-1.12.2-14.23.3.2657.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | micdoodlecore               |                          | minecraft.jar                                    | None                                     |
	| UCHIJA | opencomputers|core          | 1.7.2.67                 | minecraft.jar                                    | None                                     |
	| UCHIJA | baubles                     | 1.5.2                    | Baubles-1.12-1.5.2.jar                           | None                                     |
	| UCHIJA | ctm                         | MC1.12-0.2.3.12          | CTM-MC1.12-0.2.3.12.jar                          | None                                     |
	| UCHIJA | chisel                      | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                     | None                                     |
	| UCHIJA | crafttweaker                | 4.1.6                    | CraftTweaker2-1.12-4.1.6.jar                     | None                                     |
	| UCHIJA | mtlib                       | 3.0.4                    | MTLib-3.0.4.jar                                  | None                                     |
	| UCHIJA | modtweaker                  | 4.0.10                   | modtweaker-4.0.10.jar                            | None                                     |
	| UCHIJE | jei                         | 4.8.5.159                | jei_1.12.2-4.8.5.159.jar                         | None                                     |
	| UCHIJA | mantle                      | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                         | None                                     |
	| UCHIJA | tconstruct                  | 1.12.2-2.9.1.65          | TConstruct-1.12.2-2.9.1.65.jar                   | None                                     |
	| UCHIJA | extrautils2                 | 1.0                      | extrautils2-1.12-1.7.6.jar                       | None                                     |
	| UCHIJA | flyringbaublemod            | 0.3.1_1.12-d4e654e       | angelRingToBauble-1.12-0.3.1.50+d4e654e.jar      | None                                     |
	| UCHIJA | antiqueatlas                | 4.4.7                    | antiqueatlas-1.12.2-4.4.7.jar                    | None                                     |
	| UCHIJA | antiqueatlasoverlay         | 1.2                      | antiqueatlas-1.12.2-4.4.7.jar                    | None                                     |
	| UCHIJA | examplemod                  | 1.0                      | antiqueatlas-1.12.2-4.4.7.jar                    | None                                     |
	| UCHIJA | appleskin                   | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                       | None                                     |
	| UCHIJA | appliedenergistics2         | rv5-stable-11            | appliedenergistics2-rv5-stable-11.jar            | None                                     |
	| UCHIJA | armoreablemobs              | 1.1.2                    | armoreablemobs-1.12-1.1.6-4.jar                  | None                                     |
	| UCHIJA | bibliocraft                 | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar                | None                                     |
	| UCHIJA | biomesoplenty               | 7.0.1.2350               | BiomesOPlenty-1.12.2-7.0.1.2350-universal.jar    | None                                     |
	| UCHIJA | hammercore                  | 1.9.8.2                  | HammerCore-1.12.2-1.9.8.2.jar                    | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJA | blackholestorage            | 24r                      | BlackHoleStorage_1.12.2-24r.jar                  | None                                     |
	| UCHIJA | bookshelf                   | 2.3.541                  | Bookshelf-1.12.2-2.3.541.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | codechickenlib              | 3.1.6.339                | CodeChickenLib-1.12.2-3.1.6.339-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | redstoneflux                | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar          | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJA | brandonscore                | 2.4.0                    | BrandonsCore-1.12-2.4.0.152-universal.jar        | None                                     |
	| UCHIJA | chickenchunks               | 2.4.1.71                 | ChickenChunks-1.12.2-2.4.1.71-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | cofhcore                    | 4.3.11                   | CoFHCore-1.12.2-4.3.11.6-universal.jar           | None                                     |
	| UCHIJA | cofhworld                   | 1.1.1                    | CoFHWorld-1.12.2-1.1.1.12-universal.jar          | None                                     |
	| UCHIJA | computercraft               | 1.80pr1                  | ComputerCraft1.80pr1.jar                         | None                                     |
	| UCHIJA | ctgui                       | 1.0.0                    | CraftTweaker2-1.12-4.1.6.jar                     | None                                     |
	| UCHIJA | crafttweakerjei             | 2.0.0                    | CraftTweaker2-1.12-4.1.6.jar                     | None                                     |
	| UCHIJA | custombackgrounds           | 1.0                      | CustomBackgrounds-MC1.12-1.1.1.jar               | None                                     |
	| UCHIJA | custommainmenu              | 2.0.8                    | CustomMainMenu-MC1.12.2-2.0.8.jar                | None                                     |
	| UCHIJA | waila                       | 1.8.24                   | Hwyla-1.8.24-B39_1.12.jar                        | None                                     |
	| UCHIJA | darkutils                   | 1.8.207                  | DarkUtils-1.12.2-1.8.207.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | thermalfoundation           | 2.3.11                   | ThermalFoundation-1.12.2-2.3.11.8-universal.jar  | None                                     |
	| UCHIJA | draconicevolution           | 2.3.10                   | Draconic-Evolution-1.12-2.3.10.284-universal.jar | None                                     |
	| UCHIJA | dynamiclights               | 1.4.8                    | DynamicLights-1.12.2.jar                         | None                                     |
	| UCHIJA | dynamiclights_onfire        | 1.0.7                    | DynamicLights-1.12.2.jar                         | None                                     |
	| UCHIJA | dynamiclights_creepers      | 1.0.6                    | DynamicLights-1.12.2.jar                         | None                                     |
	| UCHIJA | dynamiclights_dropitems     | 1.1.0                    | DynamicLights-1.12.2.jar                         | None                                     |
	| UCHIJA | dynamiclights_entityclasses | 1.0.1                    | DynamicLights-1.12.2.jar                         | None                                     |
	| UCHIJA | dynamiclights_mobequipment  | 1.1.0                    | DynamicLights-1.12.2.jar                         | None                                     |
	| UCHIJA | dynamiclights_flamearrows   | 1.0.1                    | DynamicLights-1.12.2.jar                         | None                                     |
	| UCHIJA | dynamiclights_floodlights   | 1.0.3                    | DynamicLights-1.12.2.jar                         | None                                     |
	| UCHIJA | dynamiclights_otherplayers  | 1.0.9                    | DynamicLights-1.12.2.jar                         | None                                     |
	| UCHIJA | dynamiclights_theplayer     | 1.1.3                    | DynamicLights-1.12.2.jar                         | None                                     |
	| UCHIJA | enderstorage                | 2.4.2.126                | EnderStorage-1.12.2-2.4.2.126-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | extracells                  | 2.5.11                   | ExtraCells-1.12.2-2.5.11a48.jar                  | None                                     |
	| UCHIJA | galacticraftcore            | 4.0.1.174                | GalacticraftCore-1.12.2-4.0.1.174.jar            | None                                     |
	| UCHIJA | galacticraftplanets         | 4.0.1.174                | Galacticraft-Planets-1.12.2-4.0.1.174.jar        | None                                     |
	| UCHIJA | galacticrafttweaker         | 1.12.2-1.0.1             | GalacticraftTweaker-1.12.2-1.0.1.jar             | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJA | gravestone                  | 1.10.1                   | gravestone-1.10.1.jar                            | None                                     |
	| UCHIJA | ichunutil                   | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                       | None                                     |
	| UCHIJA | inventorytweaks             | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | ironchest                   | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                  | None                                     |
	| UCHIJA | login_shield                | 1.12.2-1-g24c2a5e        | Login_Shield-1.12.2-1-g24c2a5e.jar               | None                                     |
	| UCHIJA | mcjtylib_ng                 | 2.6.7                    | mcjtylib-1.12-2.6.7.jar                          | None                                     |
	| UCHIJA | metamorph                   | 1.1.5                    | metamorph-1.1.5-1.12.2.jar                       | None                                     |
	| UCHIJA | moreplanets                 | 2.0.14                   | More-Planets-1.12.2-2.0.14-GC156.jar             | b3468b224a74e296555ad7efeb35f482e6f445de |
	| UCHIJA | mousetweaks                 | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                     | None                                     |
	| UCHIJA | nd5u                        | 0.0.0                    | nd5u-1.0.jar                                     | None                                     |
	| UCHIJA | opencomputers               | 1.7.2.67                 | OpenComputers-MC1.12.2-1.7.2.67.jar              | None                                     |
	| UCHIJA | thermalexpansion            | 5.3.11                   | ThermalExpansion-1.12.2-5.3.11.14-universal.jar  | None                                     |
	| UCHIJA | omlib                       | 3.0.0-140                | omlib-1.12.2-3.0.0-140.jar                       | None                                     |
	| UCHIJA | openablewindows             | 0.0.1                    | openablewindows-1.0.jar                          | None                                     |
	| UCHIJA | openglasses                 | 1.5.5                    | OpenGlasses-MC1.12.2-1.5.5.jar                   | None                                     |
	| UCHIJA | openmodularturrets          | 3.0.0-243                | openmodularturrets-1.12.2-3.0.0-243.jar          | None                                     |
	| UCHIJA | openprinter                 | 0.1.0.1                  | OpenPrinter-1.12.2-0.1.0.1.jar                   | None                                     |
	| UCHIJA | oredicttips                 | 2.0.2                    | OreDictTips-1.12-2.0.2.jar                       | None                                     |
	| UCHIJA | plethora-core               | 1.1.11                   | plethora-1.12.2-1.1.11.jar                       | None                                     |
	| UCHIJA | plethora                    | 1.1.11                   | plethora-1.12.2-1.1.11.jar                       | None                                     |
	| UCHIJA | reauth                      | 3.5.2                    | ReAuth-3.5.2.jar                                 | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| UCHIJA | resourceloader              | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar                | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJA | rftools                     | 7.33                     | rftools-1.12-7.33.jar                            | None                                     |
	| UCHIJA | rftoolscontrol              | 1.8.1                    | rftoolsctrl-1.12-1.8.1.jar                       | None                                     |
	| UCHIJA | rftoolsdim                  | 5.53                     | rftoolsdim-1.12-5.53.jar                         | None                                     |
	| UCHIJA | rftoolspower                | 1.0.0                    | rftoolspower-1.12-1.0.0.jar                      | None                                     |
	| UCHIJA | lteleporters                | 1.12.2-3.0.2             | simpleteleporters-1.12.2-3.0.2.jar               | None                                     |
	| UCHIJA | solarfluxreborn             | 3.50r                    | SolarFluxReborn_1.12.2-3.50r.jar                 | None                                     |
	| UCHIJA | sync                        | 7.0.2                    | Sync-1.12.2-7.0.2.jar                            | None                                     |
	| UCHIJA | thebetweenlands             | 3.3.7                    | TheBetweenlands-3.3.7-universal.jar              | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCHIJA | thedalekmod                 | (Update 47 13.47.0.6)    | thedalekmod-47.0.jar                             | None                                     |
	| UCHIJA | thermaldynamics             | 2.3.11                   | ThermalDynamics-1.12.2-2.3.11.7-universal.jar    | None                                     |
	| UCHIJA | tinkersoc                   | 0.1                      | tinkersoc-0.4.jar                                | None                                     |
	| UCHIJA | totemic                     | 1.12.2-0.10.3            | Totemic-1.12.2-0.10.3.jar                        | 21d11d7bf4d97b465382a1f95428029aac6daaea |
	| UCHIJA | toughasnails                | 3.1.0.97                 | ToughAsNails-1.12.2-3.1.0.97-universal.jar       | None                                     |
	| UCHIJA | valkyrienwarfare            | 0.9_alpha                | Valkyrien Warfare 0.9_pre_3 [HotFix].jar         | None                                     |
	| UCHIJA | justthetips                 | 1.12-1.0.1.1             | justthetips-1.12-1.0.1.1.jar                     | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MixinLoaderForge (Valkyrien Warfare 0.9_pre_3 [HotFix].jar)
  
HammerCoreCore (HammerCore-1.12.2-1.9.8.2.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.7-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.174.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
DLFMLCorePlugin (DynamicLights-1.12.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.30.14' Renderer: 'Intel(R) HD Graphics 6000'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
```

**Comment by ghost** [comment]
Most of these mods in this list are installed from the Twitch launcher. Exceptions include Galaticraft.

**Comment by SquidDev** [comment]
Can you update to the latest Forge? I'm fairly sure this is caused by MinecraftForge/MinecraftForge#4865.

**Comment by ghost** [comment]
If you are testing this through the Twitch Launcher, Twitch has the tendency to enable/disable other mods related or at least dependent on the one you disable/enable. An example is disabling JEI will disable Just Enough Resources and Twilight Forest (theres more too, but that's not important). Re-enabling JER will re-enable JEI, but re-enabling Twilight Forest does not.

**Comment by ghost** [comment]
I will check my version of Forge and update if I can.

**Comment by ghost** [comment]
It works. I am now using forge-14.23.3.2668. Thanks for pointing that out!

**Comment by SquidDev** [comment]
Great!
