### ISSUE TITLE
Log Exceptions when getting items from Chest

### ISSUE THREAD

**Issue by JomerDev** [SquidDev-CC/ccjam-2016#109]
I'm seeing a lot of exceptions when a computer calls .list() and .pushItems() on a chest.

```
[Server thread/ERROR] [Plethora]: Failed to call IComputerAccess.getAvailablePeripheral
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.squiddev.plethora.integration.computercraft.TransferComputerAccess.getTransferLocation(TransferComputerAccess.java:43) ~[TransferComputerAccess.class:?]
	at org.squiddev.plethora.integration.computercraft.TransferComputerAccess.getTransferLocation(TransferComputerAccess.java:19) ~[TransferComputerAccess.class:?]
	at org.squiddev.plethora.core.TransferRegistry.getTransferPart(TransferRegistry.java:110) ~[TransferRegistry.class:?]
	at org.squiddev.plethora.core.TransferRegistry.getTransferPart(TransferRegistry.java:83) ~[TransferRegistry.class:?]
	at org.squiddev.plethora.core.PartialContext.getTransferLocation(PartialContext.java:139) ~[PartialContext.class:?]
	at org.squiddev.plethora.integration.vanilla.method.MethodsInventoryTransfer.lambda$pushItems$0(MethodsInventoryTransfer.java:41) ~[MethodsInventoryTransfer.class:?]
	at org.squiddev.plethora.core.executor.DefaultExecutor$Task.execute(DefaultExecutor.java:83) [DefaultExecutor$Task.class:?]
	at dan200.computercraft.core.lua.CobaltLuaMachine$3$1$1.execute(CobaltLuaMachine.java:379) [CobaltLuaMachine$3$1$1.class:?]
	at dan200.computercraft.core.computer.MainThread.executePendingTasks(MainThread.java:57) [MainThread.class:?]
	at dan200.computercraft.shared.proxy.ComputerCraftProxyCommon$ForgeHandlers.onServerTick(ComputerCraftProxyCommon.java:690) [ComputerCraftProxyCommon$ForgeHandlers.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1635_ForgeHandlers_onServerTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.RuntimeException: You are not attached to this Computer
	at dan200.computercraft.core.apis.PeripheralAPI$PeripheralWrapper.getAvailablePeripheral(PeripheralAPI.java:214) ~[PeripheralAPI$PeripheralWrapper.class:?]
	... 20 more
```

**Comment by SquidDev** [comment]
As a minor update, we've been running the above commit on a server for a bit and all our `You are not attached to this Computer` errors have gone. I've a couple of other things I want to implement, then I'll push a new release.
