### ISSUE TITLE
GameProfile lookup service spam with Sponge

### ISSUE THREAD

**Issue by inklit** [SquidDev-CC/ccjam-2016#11]
The FakePlayer that Plethora creates causes this to be spammed infinitely in the console with no stops.
I am aware that this is probably not your bug but in fact is likely Sponge's fault, but I'd like to let you know about  it so you can possibly work with Sponge to fix it.

```
[14:24:32] [pool-2-thread-1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@34201b1f[id=ebcda071-3ef5-4f4a-849d-c078264010c4,name=,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
        at net.minecraft.server.management.PlayerProfileCache.lookupByIds(SourceFile:249) ~[lt.class:?]
        at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(SourceFile:284) ~[lt.class:?]
        at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:1.8.9-1890-4.2.0-BETA-1625]
        at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$1(Functional.java:131) ~[Functional.class:1.8.9-1890-4.2.0-BETA-1625]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by SquidDev** [comment]
A temporary fix would be to add `41c82c87-7afb-4024-ba57-13d2c99cae77` to the `invalid-lookup-uuids` setting.

**Comment by SquidDev** [comment]
I'm pretty sure there is nothing wrong with my code (or sponge's). It appears the correct solution is adding the UUID to the invalid list. If I'm wrong I'm happy to fix this though :smile:.

**Comment by inklit** [comment]
Do you mean to add `ebcda071-3ef5-4f4a-849d-c078264010c4` to the `invalid-lookup-uuids` setting?
That is the UUID shown in the error, and that is also the UUID that you create the FakePlayer with.
`41c82c87-7afb-4024-ba57-13d2c99cae77` is already on the `invalid-lookup-uuids` list.
I think that this will solve the issue though, thanks.
Let me try it and I will get back.

EDIT:
I tried adding `ebcda071-3ef5-4f4a-849d-c078264010c4` to the list, and it did not seem to fix the problem.
As I mentioned before, the UUID you mentioned is already on the list.

**Comment by SquidDev** [comment]
Yeah, sorry: accidently had the wrong file open. Uggrh: I'll have another look.

**Comment by inklit** [comment]
Actually I'm stupid...it seems that fix does actually work but when I edited my file remotely the server rejected my upload and didn't actually notify me.
My bad.

**Comment by inklit** [comment]
Ugh...nevermind. It fixed it temporarily but it quickly broke, as this is obviously not a bug with your code leave this closed, but I thought I'd let you know.
