### ISSUE TITLE
Chat recorders dont behave correctly in SpongeForge 3323

### ISSUE THREAD

**Issue by Lemmmy** [SquidDev-CC/ccjam-2016#131]
Using `.say("foo")` on a creative chat recorder yields this error:

```
[09:09:18] [Server thread/ERROR] [Plethora]: Unexpected error
java.lang.ClassCastException: org.spongepowered.mod.SpongeModGame cannot be cast to net.minecraft.entity.player.EntityPlayerMP
        at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostServerChatEvent(SpongeToForgeEventFactory.java:309) ~[SpongeToForgeEventFactory.class:1.12.2-2705-7.1.0-BETA-3323]
        at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostForgeEvent(SpongeToForgeEventFactory.java:242) ~[SpongeToForgeEventFactory.class:1.12.2-2705-7.1.0-BETA-3323]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:337) ~[SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3323]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:428) ~[SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3323]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:403) ~[SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3323]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:446) ~[SpongeEventManager.class:1.12.2-2705-7.1.0-BETA-3323]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:225) ~[SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3323]
        at org.spongepowered.common.text.chat.ChatUtil.sendMessage(ChatUtil.java:60) ~[ChatUtil.class:1.12.2-2705-7.1.0-BETA-3323]
        at net.minecraft.server.management.PlayerList.func_148544_a(PlayerList.java:2091) ~[pl.class:?]
        at org.squiddev.plethora.gameplay.modules.methods.MethodsChatCreative$1.call(MethodsChatCreative.java:53) ~[MethodsChatCreative$1.class:?]
        at org.squiddev.plethora.gameplay.modules.methods.MethodsChatCreative$1.call(MethodsChatCreative.java:36) ~[MethodsChatCreative$1.class:?]
        at org.squiddev.plethora.core.executor.Task.update(Task.java:41) [Task.class:?]
        at org.squiddev.plethora.core.executor.ComputerAccessExecutor$BlockingTask.update(ComputerAccessExecutor.java:129) [ComputerAccessExecutor$BlockingTask.class:?]
        at org.squiddev.plethora.core.executor.TaskRunner.func_73660_a(TaskRunner.java:32) [TaskRunner.class:?]
        at org.squiddev.plethora.gameplay.modules.TileManipulator.func_73660_a(TileManipulator.java:225) [TileManipulator.class:?]
        at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:231) [TrackingUtil.class:1.12.2-2705-7.1.0-BETA-3323]
        at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2880) [oo.class:?]
        at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zlm000(WorldServer.java:2867) [oo.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:6638) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2300) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

Using `.say("foo")` on a regular chat recorder simply says "Cannot post to chat", with no further information and no errors in console.

**Comment by SquidDev** [comment]
Probably not on our end - I believe this is SpongePowered/SpongeForge#2002 again.

**Comment by SquidDev** [comment]
Fixed in Sponge
