### ISSUE TITLE
getItem() errors with framed chests in BiblioCraft 2.4.5

### ISSUE THREAD

**Issue by Lemmmy** [SquidDev-CC/ccjam-2016#143]
The following error is logged in the console:

```
[17:42:52] [Server thread/ERROR] [Plethora]: Unexpected error
java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityFramedChest.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
        at jds.bibliocraft.tileentities.TileEntityFramedChest.getStackInSlot(TileEntityFramedChest.java) ~[TileEntityFramedChest.class:?]
        at org.squiddev.plethora.integration.vanilla.method.MethodsInventory.lambda$getItem$0(MethodsInventory.java:49) ~[MethodsInventory.class:?]
        at org.squiddev.plethora.core.executor.Task.update(Task.java:41) [Task.class:?]
        at org.squiddev.plethora.core.executor.ComputerAccessExecutor$BlockingTask.update(ComputerAccessExecutor.java:129) [ComputerAccessExecutor$BlockingTask.class:?]
        at org.squiddev.plethora.core.executor.TaskRunner.func_73660_a(TaskRunner.java:32) [TaskRunner.class:?]
        at org.squiddev.plethora.core.PlethoraCore.onServerTick(PlethoraCore.java:127) [PlethoraCore.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_166_PlethoraCore_onServerTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:682) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:639) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

```

And the following ingame:
![](https://you.wouldnot.download/a-mighty-wealth.png)

Replicated with an oak framed chest:
![](https://you.wouldnot.download/a-dutch-diarist.png)

**Comment by SquidDev** [comment]
This is effectively a bug in Forge's remapper. `IInventory` and `IItemHandler` both define `getStackInSlot` in the deobfuscated sources, but this is converted to `func_70301_a` in the obfuscated code.

The best workaround here is for bibliocraft to define their `IItemHandler` instance in a separate class, or just use Forge's built-in wrapper.

**Comment by shelbykauth** [comment]
Alright, thanks.  Sorry I didn't see the duplicate.
