### ISSUE TITLE
Java.lang.NullPointerException on getBlockMeta using scanner

### ISSUE THREAD

**Issue by kepler155c** [SquidDev-CC/ccjam-2016#182]
On switchcraft, I'm getting that exception when inspecting quark:chute.

**Comment by SquidDev** [comment]
Can you try to reproduce in a single player world and give me your log file?

**Comment by kepler155c** [comment]
```
java.lang.NullPointerException: null
	at net.minecraftforge.items.wrapper.SidedInvWrapper.hashCode(SidedInvWrapper.java:66) ~[SidedInvWrapper.class:?]
	at it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap.getInt(Object2IntOpenHashMap.java:473) ~[fastutil-7.1.0.jar:?]
	at org.squiddev.plethora.core.ConverterRegistry.extendConverted(ConverterRegistry.java:71) ~[ConverterRegistry.class:?]
	at org.squiddev.plethora.core.Context.makeChild(Context.java:52) ~[Context.class:?]
	at org.squiddev.plethora.core.Context.makeChild(Context.java:64) ~[Context.class:?]
	at org.squiddev.plethora.core.Context.makeChild(Context.java:15) ~[Context.class:?]
	at org.squiddev.plethora.gameplay.modules.methods.MethodsScanner.lambda$getBlockMeta$0(MethodsScanner.java:89) ~[MethodsScanner.class:?]
	at org.squiddev.plethora.core.executor.Task.update(Task.java:41) [Task.class:?]
	at org.squiddev.plethora.core.executor.ComputerAccessExecutor$BlockingTask.update(ComputerAccessExecutor.java:129) [ComputerAccessExecutor$BlockingTask.class:?]
	at org.squiddev.plethora.core.executor.TaskRunner.func_73660_a(TaskRunner.java:32) [TaskRunner.class:?]
	at org.squiddev.plethora.gameplay.neural.NeuralComputer.update(NeuralComputer.java:129) [NeuralComputer.class:?]
	at org.squiddev.plethora.gameplay.neural.ItemNeuralInterface.onUpdate(ItemNeuralInterface.java:181) [ItemNeuralInterface.class:?]
	at org.squiddev.plethora.gameplay.neural.ItemNeuralInterface.onWornTick(ItemNeuralInterface.java:270) [ItemNeuralInterface.class:?]
	at baubles.common.event.EventHandlerEntity.playerTick(EventHandlerEntity.java:96) [EventHandlerEntity.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_196_EventHandlerEntity_playerTick_PlayerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370) [FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_184808_cD(EntityPlayer.java:378) [aed.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) [aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
```

**Comment by SquidDev** [comment]
This is a Quark bug. See CoFH/Feedback#195, ForestryMC/ForestryMC#1542 for other instances of this - there's nothing I can do about it, but you might be able to report it to their issue tracker.
