### ISSUE TITLE
Unable to launch game

### ISSUE THREAD

**Issue by inklit** [SquidDev-CC/ccjam-2016#5]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.8.9-1.5.22.6.jar)
  TweaksLoadingPlugin (CCTweaks-1.8.9-1.0.1.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 7/6/16 1:30 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraft.client.model.ModelBlaze.field_78105_b from class org.squiddev.plethora.client.RenderInterfaceLiving
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:739)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.client.model.ModelBlaze.field_78105_b from class org.squiddev.plethora.client.RenderInterfaceLiving
    at org.squiddev.plethora.client.RenderInterfaceLiving.getHead(RenderInterfaceLiving.java:81)
    at org.squiddev.plethora.client.RenderInterfaceLiving.inject(RenderInterfaceLiving.java:51)
    at org.squiddev.plethora.client.RenderInterfaceLiving.inject(RenderInterfaceLiving.java:44)
    at org.squiddev.plethora.client.RenderInterfaceLiving.clientInit(RenderInterfaceLiving.java:24)
    at org.squiddev.plethora.registry.Registry$RegisterWrapperClient.init(Registry.java:134)
    at org.squiddev.plethora.registry.Registry.init(Registry.java:71)
    at org.squiddev.plethora.Plethora.init(Plethora.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737)
    ... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 7 (amd64) version 6.1
    CPU: 16x Intel(R) Xeon(R) CPU L5520 @ 2.27GHz
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 788721368 bytes (752 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1902 Optifine OptiFine_1.8.9_HD_U_H6 13 mods loaded, 13 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHI    FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
    UCHI    Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
    UCHI    OpenComputers|Core{1.5.22.6} [OpenComputers (Core)] (minecraft.jar) 
    UCHI    <CCTweaks ASM>{1.0.1} [<CCTweaks ASM>] (minecraft.jar) 
    UCHI    ComputerCraft{1.79} [ComputerCraft] (ComputerCraft1.79 (1).jar) 
    UCHI    CCTweaks{1.0.1} [CCTweaks] (CCTweaks-1.8.9-1.0.1.jar) 
    UCHI    chunkloaderz{1.0.3} [ChunkLoaderZ] (ChunkLoaderZ-1.8.9-1.0.3.jar) 
    UCHI    IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770 (2).jar) 
    UCHI    JEI{2.28.9.176} [Just Enough Items] (jei_1.8.9-2.28.9.176.jar) 
    UCHI    MoreFurnaces{1.5.1} [More Furnaces] (MoreFurnaces-1.5.1-MC1.8.9.jar) 
    UCHI    OpenComputers{1.5.22.6} [OpenComputers] (OpenComputers-MC1.8.9-1.5.22.6.jar) 
    UCHE    Plethora{1.0.0-beta0} [Plethora] (plethora-1.8.9-1.0.0-beta0.jar) 
    Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.8.9-1.5.22.6.jar)
  li.cil.oc.common.asm.ClassTransformer
TweaksLoadingPlugin (CCTweaks-1.8.9-1.0.1.jar)
  org.squiddev.cctweaks.core.asm.ASMTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.51' Renderer: 'GeForce GTX 970/PCIe/SSE2'
    OptiFine Version: OptiFine_1.8.9_HD_U_H6
    Render Distance Chunks: 2
    Mipmaps: 0
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: null
    OpenGlVersion: 4.5.0 NVIDIA 364.51
    OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
    OpenGlVendor: NVIDIA Corporation
    CpuCount: 16
```

Game is unable to launch.

**Comment by SquidDev** [comment]
It looks like the access transformer isn't loading. I'll have a look. Thanks!

Can you reproduce with just plethora?

**Comment by inklit** [comment]
Yes, it is reproducable with just Plethora (and ComputerCraft 1.79 of course).

If it helps, here is a crash log with just ComputerCraft and Plethora.

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 7/6/16 3:11 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraft.client.model.ModelBlaze.field_78105_b from class org.squiddev.plethora.client.RenderInterfaceLiving
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:739)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.client.model.ModelBlaze.field_78105_b from class org.squiddev.plethora.client.RenderInterfaceLiving
    at org.squiddev.plethora.client.RenderInterfaceLiving.getHead(RenderInterfaceLiving.java:81)
    at org.squiddev.plethora.client.RenderInterfaceLiving.inject(RenderInterfaceLiving.java:51)
    at org.squiddev.plethora.client.RenderInterfaceLiving.inject(RenderInterfaceLiving.java:44)
    at org.squiddev.plethora.client.RenderInterfaceLiving.clientInit(RenderInterfaceLiving.java:24)
    at org.squiddev.plethora.registry.Registry$RegisterWrapperClient.init(Registry.java:134)
    at org.squiddev.plethora.registry.Registry.init(Registry.java:71)
    at org.squiddev.plethora.Plethora.init(Plethora.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737)
    ... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 781939128 bytes (745 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1902 5 mods loaded, 5 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHI    mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHI    FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
    UCHI    Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
    UCHI    ComputerCraft{1.79} [ComputerCraft] (ComputerCraft1.79.jar) 
    UCHE    Plethora{1.0.0-beta0} [Plethora] (plethora-1.8.9-1.0.0-beta0.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.51' Renderer: 'GeForce GTX 970/PCIe/SSE2'
```

**Comment by SquidDev** [comment]
Woops. Forgot you had to register it manually. I should know by now to test these things in a non-dev environment. Anyway, I've [updated the download](https://github.com/SquidDev-CC/plethora/releases/tag/v1.0-ccjam).

**Comment by inklit** [comment]
Thanks, this works.

Do you happen to have another place I can contact you? I want to put this on my server but there's a lot of questions I have and some features that I'd like to be added or changed.

**Comment by SquidDev** [comment]
If you have a ComputerCraft forums account I'm on there a fair amount. I'm also on [Gitter](https://gitter.im/) if you want to PM me there. On the subject of adding/changing: do check the other issues. There is a lot of stuff I'm planning to implement which should help make it more balanced.
