### ISSUE TITLE
Compatibility with CC: Tweaked

### ISSUE THREAD

**Issue by chimericdream** [SquidDev-CC/ccjam-2016#70]
Any plans to make this optionally compatible with CC: Tweaked rather than relying explicitly on the main CC mod?

**Comment by SquidDev** [comment]
I presume you're referring to the Curse dependencies - there isn't anything within the mod which requires a particular version of CC.

It's honestly never something I've thought about - I don't use the Curse/Twitch launcher so it's never occurred to me :). I've added optional dependencies for CC and all forks which I'm aware of - let me know if it doesn't work as expected.

**Comment by jmc529** [comment]
I think he might be referring to the crash caused by your 1.2 version of CC: Tweaked and 1.1.8 version of plethora. 
@SquidDev 
At least I am getting that crash, MC 1.12.2:

<details>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.0.4.1.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-75-core.jar)
  llibrary (llibrary-1.7.8-1.12.2.jar)
  LoadingPlugin ([1.12] VersionChecker-1.3.0.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 12/7/17 3:21 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Plethora (plethora)
Caused by: java.lang.NoClassDefFoundError: dan200/computercraft/core/apis/ILuaAPI
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663)
	at java.lang.Class.getConstructor0(Class.java:3067)
	at java.lang.Class.getDeclaredConstructor(Class.java:2170)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findConstructor(ReflectionHelper.java:254)
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.<init>(EntityEntryBuilder.java:284)
	at net.minecraftforge.fml.common.registry.EntityEntry$1.<init>(EntityEntry.java:46)
	at net.minecraftforge.fml.common.registry.EntityEntry.init(EntityEntry.java:46)
	at net.minecraftforge.fml.common.registry.EntityEntry.<init>(EntityEntry.java:40)
	at net.minecraftforge.fml.common.registry.EntityRegistry.doModEntityRegistration(EntityRegistry.java:183)
	at net.minecraftforge.fml.common.registry.EntityRegistry.registerModEntity(EntityRegistry.java:151)
	at org.squiddev.plethora.gameplay.minecart.EntityMinecartComputer$MinecartModule.preInit(EntityMinecartComputer.java:595)
	at org.squiddev.plethora.gameplay.registry.Registry$RegisterWrapper.preInit(Registry.java:121)
	at org.squiddev.plethora.gameplay.registry.Registry$RegisterWrapperClient.preInit(Registry.java:158)
	at org.squiddev.plethora.gameplay.registry.Registry.preInit(Registry.java:79)
	at org.squiddev.plethora.gameplay.Plethora.preInit(Plethora.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: dan200.computercraft.core.apis.ILuaAPI
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 56 more
Caused by: java.lang.NullPointerException 
</details>

**Comment by SquidDev** [comment]
Ahhh, that would make sense. I'd tested that everything worked with CC: Tweaked 1.80pr1.1, but not 1.80pr1.2. I'd forgotten that Plethora touched a couple of CC internals, which was causing issues here.

I've pushed a new version of CC: Tweaked which should fix these issues - it's currently under review so should show up in the next couple of hours.
