### ISSUE TITLE
Ticking Screen crash

### ISSUE THREAD

**Issue by hugeblank** [SquidDev-CC/ccjam-2016#74]
[crash-2018-01-14_16.43.33-client.txt](https://github.com/SquidDev-CC/plethora/files/1629992/crash-2018-01-14_16.43.33-client.txt)
I pulled a keyboard out of a chest that was attached to a computer behind a wall. I right clicked on it to type some stuff in, and it seems to have disliked me doing that.

**Comment by SquidDev** [comment]
```
java.lang.NullPointerException: Ticking screen
	at org.squiddev.plethora.gameplay.client.gui.GuiKeyboard.func_73876_c(GuiKeyboard.java:57)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1777)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
```

**Comment by SquidDev** [comment]
This should be impossible: it implies `GuiKeyboard.initGui` was never called. I've tried to reproduce on your modpack, and it all seems to work, so I'm not really sure what's happening.

I'm going to close this for now - if it occurs again do comment and I'll reopen.

**Comment by SquidDev** [comment]
Reopening so I can mark as fixed with a commit. The lesson here kids is attach your logs as well as crash report.

**Comment by hugeblank** [comment]
Alright my bad. Glad it was fixed :)
